# Generated by Django 5.0.7 on 2024-07-17 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('tracking_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Third Party Service',
                'verbose_name_plural': 'Third Party Services',
                'db_table': 'del_third_party_services',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('delivery_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('delivery_address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='sales.sale')),
                ('third_party_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='delivery.thirdpartyservice')),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'db_table': 'del_delivery_orders',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderDetail',
            fields=[
                ('delivery_order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order_details', to='delivery.deliveryorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order_details', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Delivery Order Detail',
                'verbose_name_plural': 'Delivery Order Details',
                'db_table': 'del_delivery_order_details',
            },
        ),
    ]
