# Generated by Django 5.0.6 on 2024-05-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='deliveryorderdetail',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order_details', to='delivery.deliveryorder'),
        ),
        migrations.AddField(
            model_name='deliveryorderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order_details', to='inventory.product'),
        ),
    ]
