# Generated by Django 5.0.6 on 2024-05-31 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryteam',
            name='members',
            field=models.ManyToManyField(related_name='delivery_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='delivery.deliveryteam'),
        ),
    ]
