# Generated by Django 5.0.6 on 2024-06-23 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Debito', 'Debit'), ('Credito', 'Credit'), ('PayPal', 'PayPal')], max_length=10)),
                ('provider', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('expire_date', models.DateField()),
                ('name_on_account', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'use_PaymentMethods',
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('client_id', 'account_number'), name='unique_client_account'),
        ),
    ]
