# Generated by Django 5.0.7 on 2024-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paymentmethod_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expire_date',
            field=models.CharField(max_length=10),
        ),
    ]
