# Generated by Django 5.0.6 on 2024-05-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pro_Phases',
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('productionLine_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pro_ProductionLines',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('production_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
            ],
            options={
                'db_table': 'pro_ProductionOrders',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'pro_ProductionOrdersDetails',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_phase_date', models.DateTimeField()),
                ('exit_phase_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'pro_ProductionOrders-Phases',
            },
        ),
        migrations.CreateModel(
            name='ProductionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'pro_production_phases',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('factory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.city')),
            ],
            options={
                'db_table': 'pro_Factories',
            },
        ),
        migrations.CreateModel(
            name='FactoryManager',
            fields=[
                ('factory_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.factory')),
            ],
            options={
                'db_table': 'pro_FactoryManagers',
            },
        ),
    ]
