# Generated by Django 5.0.6 on 2024-05-30 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pro_Phases',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('factory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.city')),
            ],
            options={
                'db_table': 'pro_Factories',
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('productionLine_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.factory')),
                ('production_line_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_production_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pro_ProductionLines',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('production_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.factory')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse_to_deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_orders', to='inventory.warehouse')),
                ('warehouse_to_retrieve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieve_orders', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'pro_ProductionOrders',
            },
        ),
        migrations.CreateModel(
            name='FactoryManager',
            fields=[
                ('factory_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.factory')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pro_FactoryManagers',
                'unique_together': {('factory', 'manager')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.productionorder')),
            ],
            options={
                'db_table': 'pro_ProductionOrdersDetails',
                'unique_together': {('production_order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_phase_date', models.DateTimeField()),
                ('exit_phase_date', models.DateTimeField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.phase')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.productionorder')),
            ],
            options={
                'db_table': 'pro_ProductionOrders-Phases',
                'unique_together': {('production_order', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='ProductionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.phase')),
                ('productionLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.productionline')),
            ],
            options={
                'db_table': 'pro_production_phases',
                'unique_together': {('productionLine', 'phase')},
            },
        ),
    ]
