# Generated by Django 5.0.7 on 2024-07-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='after_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_phases', to='production_line.phase'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='state',
            field=models.CharField(choices=[('In Use', 'IN USE'), ('Free', 'FREE')], default='Free', max_length=20),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='pl_assigned',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_line.productionline'),
        ),
        migrations.AlterField(
            model_name='productionorderphase',
            name='entry_phase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionorderphase',
            name='exit_phase_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
