# Generated by Django 5.0.6 on 2024-06-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_line', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionline',
            old_name='nombre',
            new_name='name',
        ),
    ]
