# Generated by Django 5.0.7 on 2024-07-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_line', '0002_phase_after_phase_productionline_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='warehouse',
        ),
    ]
