# Generated by Django 5.0.7 on 2024-07-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_line', '0003_remove_productionline_warehouse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factorymanager',
            unique_together=set(),
        ),
    ]
