# Generated by Django 5.0.6 on 2024-06-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('production_line', '0004_factory_status_phase_status_productionline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
