# Generated by Django 5.0.6 on 2024-07-10 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_operationlog_product_and_more'),
        ('production_line', '0005_productionline_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderWarehouseRetrievalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_line.productionorder')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'pro_production_orders_warehouses_retrieveal_detail',
                'unique_together': {('production_order', 'warehouse', 'raw_material')},
            },
        ),
    ]
