# Generated by Django 5.0.6 on 2024-07-10 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_line', '0006_productionorderwarehouseretrievaldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='warehouse_to_retrieve',
        ),
    ]
