# Generated by Django 5.0.6 on 2024-06-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('attached_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inv_attached_file',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'inv_category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inv_city',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('item_type', models.CharField(choices=[('Product', 'Product'), ('RawMaterial', 'RawMaterial')], max_length=12)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'inv_inventory',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('operation_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type_operation', models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove')], max_length=6)),
            ],
            options={
                'db_table': 'inv_operation_log',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to='product_icons/')),
            ],
            options={
                'db_table': 'inv_product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'inv_product_image',
            },
        ),
        migrations.CreateModel(
            name='ProductRawMaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'inv_product_raw_material_list',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('raw_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to='product_icons/')),
            ],
            options={
                'db_table': 'inv_raw_material',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'inv_raw_material_supplier',
            },
        ),
        migrations.CreateModel(
            name='RestockRequest',
            fields=[
                ('restock_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=9)),
            ],
            options={
                'db_table': 'inv_restock_request',
            },
        ),
        migrations.CreateModel(
            name='RestockRequestWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'inv_restock_request_warehouse',
            },
        ),
        migrations.CreateModel(
            name='RestockRequestWarehouseRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'inv_restock_request_warehouse_raw_material',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inv_state',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('RFC', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('rating', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
            ],
            options={
                'db_table': 'inv_supplier',
            },
        ),
        migrations.CreateModel(
            name='UserWarehouseAssignment',
            fields=[
                ('user_warehouse_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('removed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inv_user_warehouse_assignment',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
            ],
            options={
                'db_table': 'inv_warehouse',
            },
        ),
    ]
