# Generated by Django 5.0.6 on 2024-05-28 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'inv_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
                ('image_icon', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'inv_product',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('RFC', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('rating', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
            ],
            options={
                'db_table': 'inv_supplier',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
            ],
            options={
                'db_table': 'inv_warehouse',
            },
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('attached_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=100)),
                ('user_uploader', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'db_table': 'inv_attached_file',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'db_table': 'inv_product_image',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('raw_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image_icon', models.CharField(blank=True, max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
            options={
                'db_table': 'inv_raw_material',
            },
        ),
        migrations.CreateModel(
            name='RestockRequest',
            fields=[
                ('restock_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=9)),
                ('requested_by', models.IntegerField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inv_restock_request',
            },
        ),
        migrations.CreateModel(
            name='RestockRequestsWarehouse',
            fields=[
                ('restock_requests_warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=9)),
                ('requested_from', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.restockrequest')),
                ('request_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_request_warehouse', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inv_restock_requests_warehouse',
            },
        ),
        migrations.CreateModel(
            name='UserWarehouseAssignment',
            fields=[
                ('user_warehouse_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('manager_user', models.IntegerField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inv_user_warehouse_assignment',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('operation_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type_operation', models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove')], max_length=6)),
                ('op_log_user', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inv_operation_log',
            },
        ),
        migrations.CreateModel(
            name='RestockRequestsWarehouseRawMaterial',
            fields=[
                ('restock_requests_warehouse_raw_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial')),
                ('request_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.restockrequestswarehouse')),
            ],
            options={
                'db_table': 'inv_restock_requests_warehouse_raw_material',
                'unique_together': {('request_warehouse', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='RawMaterialSupplier',
            fields=[
                ('raw_material_supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
            options={
                'db_table': 'inv_raw_material_supplier',
                'unique_together': {('raw_material', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('item_type', models.CharField(choices=[('Product', 'Product'), ('RawMaterial', 'RawMaterial')], max_length=12)),
                ('stock', models.IntegerField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inv_inventory',
                'unique_together': {('item_id', 'item_type', 'warehouse')},
            },
        ),
    ]
