# Generated by Django 5.0.7 on 2024-07-21 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rawmaterial_purchase_price_rawmaterial_supplier'),
        ('production_line', '0003_remove_productionline_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
        migrations.AddField(
            model_name='restockrequestwarehouse',
            name='to_factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restock_request_Factory', to='production_line.factory'),
            preserve_default=False,
        ),
       
    ]
