# Generated by Django 5.0.7 on 2024-07-22 04:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_restockrequestwarehouse_unique_together_and_more'),
        ('production_line', '0003_remove_productionline_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restockrequestwarehouse',
            name='production_order_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='restock_request_PO', to='production_line.productionorder'),
            preserve_default=False,
        ),
    ]
