# Generated by Django 5.0.6 on 2024-07-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
