# Generated by Django 5.0.7 on 2024-08-01 01:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_restockrequestwarehouse_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AlterField(
            model_name='userwarehouseassignment',
            name='assigned_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userwarehouseassignment',
            name='removed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
]
