# Generated by Django 5.0.6 on 2024-06-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reports_id', models.AutoField(primary_key=True, serialize=False)),
                ('solution', models.CharField(max_length=200)),
                ('results', models.CharField(max_length=200)),
                ('suggestions', models.CharField(max_length=200)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tic_Reports',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved')], max_length=10)),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_due_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_close_date', models.DateTimeField(blank=True, null=True)),
                ('phase', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'tic_Tickets',
            },
        ),
    ]
