# Generated by Django 5.0.6 on 2024-05-30 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved')], max_length=10)),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_due_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_close_date', models.DateTimeField(blank=True, null=True)),
                ('phase', models.PositiveSmallIntegerField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to=settings.AUTH_USER_MODEL)),
                ('assignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tic_Tickets',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reports_id', models.AutoField(primary_key=True, serialize=False)),
                ('solution', models.CharField(max_length=200)),
                ('results', models.CharField(max_length=200)),
                ('suggestions', models.CharField(max_length=200)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tic_Reports',
            },
        ),
    ]
