# Generated by Django 5.0.6 on 2024-06-23 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='buyer',
        ),
        migrations.AddField(
            model_name='cart',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Debito', 'Debit'), ('Credito', 'Credit'), ('PayPal', 'PayPal')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='sal_carts',
        ),
        migrations.AlterModelTable(
            name='cartdetail',
            table='sal_cart_details',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='sal_payments',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sal_sales',
        ),
        migrations.AlterModelTable(
            name='saledetail',
            table='sal_sale_details',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
